// packages/react/src/Calendar.tsx
import type {
  CalendarCellState,
  CalendarOptions,
} from "@typescript-calendar-lib/core";
import {
  addDays,
  buildMonthGrid,
  createDate,
  getCalendarCellState,
  getISOWeek,
  getMonthName,
  getWeekdayHeaders,
  getWeekOfYear,
  isSameDay,
} from "@typescript-calendar-lib/core";
import { formatCellLabel } from "@typescript-calendar-lib/web";
import type {
  CSSProperties,
  KeyboardEvent as ReactKeyboardEvent,
  ReactNode,
  Ref,
} from "react";
import { getCellClasses } from "./cell-classes.ts";
import type { CalendarSize } from "./size.ts";
import { buildSizeStyle, isSizeName } from "./size.ts";
import type {
  ColorSchemeName,
  ReactColorScheme,
  ReactTheme,
  ThemeName,
} from "./themes.ts";
import { resolveColorScheme, resolveTheme } from "./themes.ts";

export type {
  CalendarCustomSize,
  CalendarSize,
  CalendarSizeName,
} from "./size.ts";

export interface CalendarProps {
  year: number;
  month: number;
  locale?: CalendarOptions["locale"];
  holidayLocale?: CalendarOptions["holidayLocale"];
  weekStart?: CalendarOptions["weekStart"];
  /** 各週の先頭に週番号（ISO/年始基準）を表示する。既定は false */
  showWeekNumbers?: boolean;
  highlight?: Date;
  /** 範囲強調 */
  range?: { from: Date; to: Date };
  /** 今日の基準日。カラースキームの today 着色に使用 */
  today?: Date;
  /** 範囲プレビュー（ホバー等の候補範囲）。is-in-range-preview クラスで視覚化される */
  rangePreview?: { from: Date; to: Date };
  /** 見た目テーマ。既定は "default" */
  theme?: ThemeName | ReactTheme;
  /** カラースキーム。既定は "default" */
  colorScheme?: ColorSchemeName | ReactColorScheme;
  /** セルサイズ。既定は "md"。{ width, height } で自由に指定できる */
  size?: CalendarSize;
  /** 狭い画面（スマホ等）でセルサイズと余白を自動調整する。既定は false（無効） */
  responsive?: boolean;
  /** root 要素に追加するスタイル。CSS変数（--cal-*）で自由に上書きできる */
  style?: CSSProperties;

  // ── インタラクション ──

  /** インタラクティブモードを有効にする。セルクリック・ホバー・キーボード選択が可能になる */
  interactive?: boolean;
  /** セルクリック時のコールバック。第2引数に該当日のデータ（cellData の戻り値）が渡る */
  onDateClick?: (date: Date, data?: unknown) => void;
  /** セルホバー時のコールバック */
  onDateHover?: (date: Date) => void;
  /** カレンダーからマウスが離れたときのコールバック */
  onDateLeave?: () => void;
  /** キーボード操作。root 要素で発火（矢印キー等を InteractiveCalendar が処理する） */
  onKeyDown?: (event: ReactKeyboardEvent<HTMLDivElement>) => void;

  // ── セル状態 ──

  /** 選択済み日付。aria-selected・aria-pressed と表示スタイルに使用 */
  selectedDate?: Date | null;
  /** カーソル位置の日付。このセルだけ tabIndex=0（roving tabindex）になる */
  cursorDate?: Date | null;
  /** ホバー中の日付。is-hovered クラスで視覚化される */
  hoveredDate?: Date | null;
  /** セル内容のカスタムレンダリング。interactive 時は button の子として描画される。第4引数に該当日のデータが渡る */
  renderCell?: (
    day: number,
    date: Date,
    state: CalendarCellState,
    data?: unknown,
  ) => ReactNode;
  /** 各セルに付与するユーザー定義データを解決する関数。実セルのみに呼ばれる */
  cellData?: (date: Date) => unknown;
  /** 選択不可日付の判定。true を返した日付は is-disabled クラスになり、インタラクティブ時は選択・ホバーできなくなる */
  isDateDisabled?: (date: Date) => boolean;

  /** root 要素への ref（React 19 の ref-as-prop） */
  ref?: Ref<HTMLDivElement>;
}

/** 月カレンダーコンポーネント */
export function Calendar({
  year,
  month,
  locale = "en",
  holidayLocale,
  weekStart = "sunday",
  showWeekNumbers = false,
  highlight,
  range,
  today,
  theme = "default",
  colorScheme = "default",
  size = "md",
  responsive = false,
  style,
  interactive = false,
  onDateClick,
  onDateHover,
  onDateLeave,
  onKeyDown,
  selectedDate = null,
  cursorDate = null,
  hoveredDate = null,
  renderCell,
  cellData,
  isDateDisabled,
  rangePreview,
  ref,
}: CalendarProps) {
  const cellDate = (day: number): Date => createDate(year, month - 1, day);
  const weekOf = (row: (number | null)[]): number | null => {
    const firstIdx = row.findIndex((d) => d !== null);
    if (firstIdx === -1) return null;
    const firstDate = createDate(year, month - 1, row[firstIdx]!);
    const weekStartDate = addDays(firstDate, -firstIdx);
    return weekStart === "monday"
      ? getISOWeek(weekStartDate)
      : getWeekOfYear(weekStartDate);
  };
  const className = (day: number): string | undefined =>
    getCellClasses(cellDate(day), {
      today,
      holidayLocale,
      highlight,
      range,
      rangePreview,
      hoveredDate,
      selected: selectedDate,
      cursorDate,
      isDateDisabled,
    }) || undefined;

  const handleCellClick = (day: number) => {
    if (interactive && onDateClick) {
      const date = cellDate(day);
      onDateClick(date, cellData?.(date));
    }
  };

  const handleCellHover = (day: number) => {
    if (interactive && onDateHover) onDateHover(cellDate(day));
  };

  const handleMouseLeave = () => {
    if (interactive && onDateLeave) onDateLeave();
  };

  const title = `${getMonthName(locale, month)} ${year}`;
  // インタラクティブ時のみ APG の grid セマンティクスを付与する。
  // 静的表示ではネイティブの table/cell セマンティクスをそのまま使う。
  const gridRole = interactive ? "grid" : undefined;
  const cellRole = interactive ? "gridcell" : undefined;

  return (
    // biome-ignore lint/a11y/noStaticElementInteractions: onMouseLeave はホバー状態クリア用の補助イベント。キーボード操作（role=grid）は独立して対応済み
    <div
      ref={ref}
      className={`calendar ${resolveTheme(theme).className}${isSizeName(size) ? ` calendar-size-${size}` : ""}${interactive ? " calendar-interactive" : ""}${responsive ? " calendar-responsive" : ""}`}
      onMouseLeave={interactive ? handleMouseLeave : undefined}
      style={{
        ...(resolveColorScheme(colorScheme) as CSSProperties),
        ...buildSizeStyle(size),
        ...style,
      }}
    >
      <div className="calendar-header">
        <h2>{title}</h2>
      </div>
      <table role={gridRole} aria-label={title} onKeyDown={onKeyDown}>
        <thead>
          <tr>
            {showWeekNumbers && (
              <th
                key="week"
                className="calendar-week"
                scope="col"
                aria-label="Week number"
              />
            )}
            {getWeekdayHeaders(locale, weekStart).map((day) => (
              <th key={day} scope="col">
                {day}
              </th>
            ))}
          </tr>
        </thead>
        <tbody>
          {buildMonthGrid(year, month, weekStart).map((row, i) => {
            if (row.every((d) => d === null)) return null;
            const week = weekOf(row);
            return (
              // biome-ignore lint/suspicious/noArrayIndexKey: 月グリッドは静的で並び順が変わらない
              <tr key={i}>
                {showWeekNumbers && week !== null && (
                  <th key="week" className="calendar-week" scope="row">
                    {week}
                  </th>
                )}
                {row.map((day, j) => {
                  if (day === null)
                    // biome-ignore lint/suspicious/noArrayIndexKey: パディングセルは位置が唯一の識別子
                    return <td key={j} role={cellRole} />;
                  const date = cellDate(day);
                  const state = getCalendarCellState(date, {
                    today,
                    highlight,
                    range,
                    isDateDisabled,
                  });
                  const data = cellData?.(date);
                  const selected =
                    selectedDate !== null && isSameDay(date, selectedDate);
                  const cursor =
                    cursorDate !== null && isSameDay(date, cursorDate);
                  return (
                    // biome-ignore lint/a11y/useAriaPropsSupportedByRole: interactive 時は td に role=gridcell が付き aria-selected は有効（role が動的なため静的解析できない）
                    <td
                      // パディングセル（key=j）との衝突を避けるため日番号に "d-" を付与する。日番号は列位置 j と異なり配列の index ではない
                      key={`d-${day}`}
                      role={cellRole}
                      tabIndex={interactive ? -1 : undefined}
                      className={className(day)}
                      aria-selected={selected || undefined}
                      aria-current={state.isToday ? "date" : undefined}
                      aria-disabled={state.isDisabled || undefined}
                    >
                      {interactive ? (
                        <button
                          type="button"
                          className="calendar-day-btn"
                          onClick={
                            state.isDisabled
                              ? undefined
                              : () => handleCellClick(day)
                          }
                          onMouseEnter={
                            state.isDisabled
                              ? undefined
                              : () => handleCellHover(day)
                          }
                          tabIndex={cursor ? 0 : -1}
                          data-cursor={cursor ? "true" : undefined}
                          aria-label={formatCellLabel(locale, year, month, day)}
                          aria-pressed={selected}
                          disabled={state.isDisabled}
                        >
                          {renderCell
                            ? renderCell(day, date, state, data)
                            : day}
                        </button>
                      ) : renderCell ? (
                        renderCell(day, date, state, data)
                      ) : (
                        day
                      )}
                    </td>
                  );
                })}
              </tr>
            );
          })}
        </tbody>
      </table>
    </div>
  );
}

export default Calendar;

// packages/svelte/src/Calendar.svelte
<script lang="ts">
  import type { CalendarCellState, CalendarOptions } from "@typescript-calendar-lib/core";
  import {
    addDays,
    buildMonthGrid,
    createDate,
    getCalendarCellState,
    getISOWeek,
    getMonthName,
    getWeekOfYear,
    getWeekdayHeaders,
    isSameDay,
  } from "@typescript-calendar-lib/core";
  import { formatCellLabel } from "@typescript-calendar-lib/web";
  import { getCellClasses } from "./cell-classes.js";
  import type { CalendarSize } from "./size.js";
  import { buildSizeStyle, isSizeName } from "./size.js";
  import type { CSSProperties } from "./style.js";
  import { styleObjectToString } from "./style.js";
  import type {
    ColorSchemeName,
    SvelteColorScheme,
    SvelteTheme,
    ThemeName,
  } from "./themes.js";
  import { resolveColorScheme, resolveTheme } from "./themes.js";

  interface CalendarProps {
    year: number;
    month: number;
    locale?: CalendarOptions["locale"];
    holidayLocale?: CalendarOptions["holidayLocale"];
    weekStart?: CalendarOptions["weekStart"];
    highlight?: Date;
    /** 範囲強調 */
    range?: { from: Date; to: Date };
    /** 範囲プレビュー（ホバー等の候補範囲）。is-in-range-preview クラスで視覚化される */
    rangePreview?: { from: Date; to: Date };
    /** 今日の基準日。カラースキームの today 着色に使用 */
    today?: Date;
    /** 選択済み日付。該当セルに is-selected クラスが付き、interactive 時は button に aria-pressed が付く */
    selected?: Date | null;
    /** カーソル位置の日付。該当セルに is-cursor クラスが付く */
    cursorDate?: Date | null;
    /** ホバー中の日付。該当セルに is-hovered クラスが付く */
    hoveredDate?: Date | null;
    /** 見た目テーマ。既定は "default" */
    theme?: ThemeName | SvelteTheme;
    /** カラースキーム。既定は "default" */
    colorScheme?: ColorSchemeName | SvelteColorScheme;
    /** セルサイズ。既定は "md"。{ width, height } で自由に指定できる */
    size?: CalendarSize;
    /** 狭い画面（スマホ等）でセルサイズと余白を自動調整する。既定は false（無効） */
    responsive?: boolean;
    /** 行の先頭に週番号を表示する。既定は false（非表示） */
    showWeekNumbers?: boolean;
    /** root 要素に追加するスタイル。CSS変数（--cal-*）で自由に上書きできる */
    style?: CSSProperties;

    // ── インタラクション ──

    /** インタラクティブモードを有効にする。セルクリック・ホバー・キーボード選択が可能になる */
    interactive?: boolean;
    /** セルクリック時のコールバック。第2引数に該当日のデータ（cellData の戻り値）が渡る */
    onDateClick?: (date: Date, data?: unknown) => void;
    /** セルホバー時のコールバック */
    onDateHover?: (date: Date) => void;
    /** カレンダーからマウスが離れたときのコールバック */
    onDateLeave?: () => void;
    /** キーボード操作。root 要素で発火（矢印キー等を InteractiveCalendar が処理する） */
    onkeydown?: (event: KeyboardEvent) => void;

    // ── セル状態 ──

    /** セル内容のカスタムレンダリング。interactive 時は button の子として描画される。第4引数に該当日のデータが渡る */
    renderCell?: (
      day: number,
      date: Date,
      state: CalendarCellState,
      data?: unknown,
    ) => string;
    /** 各セルに付与するユーザー定義データを解決する関数。実セルのみに呼ばれる */
    cellData?: (date: Date) => unknown;
    /** 選択不可日付の判定。true を返した日付は is-disabled クラスになり、インタラクティブ時は選択・ホバーできなくなる */
    isDateDisabled?: (date: Date) => boolean;
  }

  let {
    year,
    month,
    locale = "en",
    holidayLocale,
    weekStart = "sunday",
    highlight,
    range,
    rangePreview,
    today,
    selected,
    cursorDate,
    hoveredDate,
    theme = "default",
    colorScheme = "default",
    size = "md",
    responsive = false,
    showWeekNumbers = false,
    style,
    interactive = false,
    onDateClick,
    onDateHover,
    onDateLeave,
    onkeydown,
    renderCell,
    cellData,
    isDateDisabled,
  }: CalendarProps = $props();

  const cellDate = (day: number): Date => createDate(year, month - 1, day);
  const cellState = (day: number): CalendarCellState =>
    getCalendarCellState(cellDate(day), { today, holidayLocale, highlight, range, isDateDisabled });
  const cellClass = (day: number): string | undefined =>
    getCellClasses(cellDate(day), {
      today,
      holidayLocale,
      highlight,
      range,
      rangePreview,
      selected,
      cursorDate,
      hoveredDate,
      isDateDisabled,
    }) || undefined;
  const isDisabledDay = (day: number): boolean => cellState(day).isDisabled;
  const isSelectedDay = (day: number): boolean =>
    selected != null && isSameDay(cellDate(day), selected);
  const isTodayDay = (day: number): boolean =>
    today != null && isSameDay(cellDate(day), today);
  const isCursorDay = (day: number): boolean =>
    cursorDate != null && isSameDay(cellDate(day), cursorDate);
  const weekOf = (row: (number | null)[]): number | null => {
    const firstIdx = row.findIndex((d) => d !== null);
    if (firstIdx === -1) return null;
    const firstDate = createDate(year, month - 1, row[firstIdx]!);
    const weekStartDate = addDays(firstDate, -firstIdx);
    return weekStart === "monday"
      ? getISOWeek(weekStartDate)
      : getWeekOfYear(weekStartDate);
  };
  const handleCellClick = (day: number) => {
    if (interactive && onDateClick) {
      const date = cellDate(day);
      onDateClick(date, cellData?.(date));
    }
  };
  const handleCellHover = (day: number) => {
    if (interactive && onDateHover) onDateHover(cellDate(day));
  };
  const handleMouseLeave = () => {
    if (interactive && onDateLeave) onDateLeave();
  };

  // style 属性は文字列のみ受け付けるためオブジェクトを直列化する（--cal-* 変数含む）
  const rootStyle = $derived(
    styleObjectToString({
      ...resolveColorScheme(colorScheme),
      ...buildSizeStyle(size),
      ...style,
    }),
  );
</script>

<div
  class="calendar {resolveTheme(theme).className}{isSizeName(size) ? ` calendar-size-${size}` : ""}{interactive ? " calendar-interactive" : ""}{responsive ? " calendar-responsive" : ""}"
  style={rootStyle}
  role={interactive ? "group" : undefined}
  onmouseleave={interactive ? handleMouseLeave : undefined}
  onkeydown={onkeydown}
>
  <div class="calendar-header">
    <h2>{getMonthName(locale, month)} {year}</h2>
  </div>
  <table aria-label={`${getMonthName(locale, month)} ${year}`}>
    <thead>
      <tr>
        {#if showWeekNumbers}
          <th class="calendar-week" scope="col" aria-label="Week number"></th>
        {/if}
        {#each getWeekdayHeaders(locale, weekStart) as day (day)}
          <th scope="col">{day}</th>
        {/each}
      </tr>
    </thead>
    <tbody>
      {#each buildMonthGrid(year, month, weekStart) as row, i (i)}
        {#if !row.every((d) => d === null)}
          <tr>
            {#if showWeekNumbers}
              <th class="calendar-week" scope="row">{weekOf(row)}</th>
            {/if}
            {#each row as day, j (j)}
              {#if day === null}
                <td></td>
              {:else}
                <td
                  class={cellClass(day)}
                  aria-current={isTodayDay(day) ? "date" : undefined}
                  aria-disabled={isDisabledDay(day) || undefined}
                >
                  {#if interactive}
                    <button
                      type="button"
                      class="calendar-day-btn"
                      onclick={isDisabledDay(day) ? undefined : () => handleCellClick(day)}
                      onmouseenter={isDisabledDay(day) ? undefined : () => handleCellHover(day)}
                      tabindex={isCursorDay(day) ? 0 : -1}
                      data-cursor={isCursorDay(day) ? "true" : undefined}
                      aria-label={formatCellLabel(locale, year, month, day)}
                      aria-pressed={isSelectedDay(day)}
                      disabled={isDisabledDay(day)}
                    >
                      {#if renderCell}
                        {renderCell(day, cellDate(day), cellState(day), cellData?.(cellDate(day)))}
                      {:else}
                        {day}
                      {/if}
                    </button>
                  {:else if renderCell}
                    {renderCell(day, cellDate(day), cellState(day), cellData?.(cellDate(day)))}
                  {:else}
                    {day}
                  {/if}
                </td>
              {/if}
            {/each}
          </tr>
        {/if}
      {/each}
    </tbody>
  </table>
</div>
